# contextlens/core/monitor.py
"""
Token Monitor — Phase 5

Responsibility: Record, aggregate, and report on token usage,
API cost, and latency across every run in a session.

Design decisions:
  - RunMetric is a lightweight dataclass (fast to create per-run)
  - All aggregation is done lazily at report time (not on every record)
  - Percentile calculation uses numpy for accuracy
  - Budget system uses configurable daily/session limits
  - JSONL store mirrors the logger pattern (Phase 2) for consistency
  - All money is stored as float USD — no currency objects needed at this scale

Production insight: In real teams, this data feeds dashboards, 
cost-allocation reports, and automated budget alerts to Slack/PagerDuty.
"""

from __future__ import annotations

import json
import statistics
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
from loguru import logger
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich import box

from contextlens.config import config

console = Console()


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class RunMetric:
    """
    Lightweight metric snapshot for one completed LensResult.

    Designed to be created immediately after a run completes.
    Stored in JSONL — one line per run — for fast append and streaming reads.
    """
    run_id: str
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    provider: str = "unknown"
    model: str = "unknown"
    session_id: str = "default"

    # Token breakdown
    input_tokens: int = 0
    output_tokens: int = 0
    total_tokens: int = 0
    context_tokens: int = 0       # from ContextEntry (pre-API token count)

    # Cost (USD)
    estimated_cost_usd: float = 0.0

    # Latency
    api_latency_ms: float = 0.0   # just the API call
    wall_time_ms: float = 0.0     # end-to-end including logging + evaluation

    # Quality signal from evaluator (Phase 4)
    context_score: float | None = None
    context_grade: str | None = None

    # Tags from the original run (for filtering)
    tags: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["estimated_cost_usd"] = round(d["estimated_cost_usd"], 8)
        d["api_latency_ms"] = round(d["api_latency_ms"], 2)
        d["wall_time_ms"] = round(d["wall_time_ms"], 2)
        return d


@dataclass
class ProviderStats:
    """Aggregated stats for one provider within a session."""
    provider: str
    runs: int = 0
    total_tokens: int = 0
    total_cost_usd: float = 0.0
    total_latency_ms: float = 0.0
    latencies: list[float] = field(default_factory=list)

    @property
    def avg_latency_ms(self) -> float:
        return self.total_latency_ms / max(1, self.runs)

    @property
    def avg_cost_per_run(self) -> float:
        return self.total_cost_usd / max(1, self.runs)

    @property
    def avg_tokens_per_run(self) -> float:
        return self.total_tokens / max(1, self.runs)


@dataclass
class SessionReport:
    """
    Complete monitoring report for the current session.

    Generated by TokenMonitor.get_report().
    Read by the CLI 'contextlens report' command.
    Will feed the Streamlit dashboard (Phase 10).
    """
    session_id: str
    generated_at: str
    total_runs: int
    total_tokens: int
    total_cost_usd: float
    avg_tokens_per_run: float
    avg_cost_per_run_usd: float

    # Latency percentiles (ms)
    p50_latency_ms: float
    p90_latency_ms: float
    p99_latency_ms: float
    min_latency_ms: float
    max_latency_ms: float

    # Provider breakdown
    by_provider: dict[str, ProviderStats]

    # Budget tracking
    budget_usd: float | None
    budget_used_pct: float | None
    budget_status: str          # "ok" | "warning" | "exceeded" | "no_budget"

    # Quality summary (from evaluator)
    avg_context_score: float | None
    runs_passed_evaluation: int | None

    # Top issues across session
    most_expensive_run: RunMetric | None
    slowest_run: RunMetric | None

    def to_dict(self) -> dict[str, Any]:
        d = {
            "session_id": self.session_id,
            "generated_at": self.generated_at,
            "total_runs": self.total_runs,
            "total_tokens": self.total_tokens,
            "total_cost_usd": round(self.total_cost_usd, 6),
            "avg_tokens_per_run": round(self.avg_tokens_per_run, 1),
            "avg_cost_per_run_usd": round(self.avg_cost_per_run_usd, 6),
            "latency_percentiles_ms": {
                "p50": round(self.p50_latency_ms, 1),
                "p90": round(self.p90_latency_ms, 1),
                "p99": round(self.p99_latency_ms, 1),
                "min": round(self.min_latency_ms, 1),
                "max": round(self.max_latency_ms, 1),
            },
            "by_provider": {
                name: {
                    "runs": ps.runs,
                    "total_tokens": ps.total_tokens,
                    "total_cost_usd": round(ps.total_cost_usd, 6),
                    "avg_latency_ms": round(ps.avg_latency_ms, 1),
                    "avg_cost_per_run": round(ps.avg_cost_per_run, 6),
                }
                for name, ps in self.by_provider.items()
            },
            "budget": {
                "budget_usd": self.budget_usd,
                "used_pct": round(self.budget_used_pct, 2)
                    if self.budget_used_pct is not None else None,
                "status": self.budget_status,
            },
            "quality": {
                "avg_context_score": round(self.avg_context_score, 2)
                    if self.avg_context_score is not None else None,
                "runs_passed_evaluation": self.runs_passed_evaluation,
            },
        }
        return d


# ---------------------------------------------------------------------------
# Main monitor
# ---------------------------------------------------------------------------

class TokenMonitor:
    """
    Records and aggregates token usage, cost, and latency.

    One monitor per ContextLens session. Lives on the ContextLens instance.

    Usage (called internally by lens.run()):
        monitor = TokenMonitor(session_id="my_session")
        monitor.record(lens_result)           # called after each run
        report = monitor.get_report()         # called by CLI / end of session
        monitor.print_report()                # rich terminal table
    """

    def __init__(
        self,
        session_id: str = "default",
        budget_usd: float | None = None,
        log_dir: Path | None = None,
    ):
        """
        Args:
            session_id:  Session name — matches the context logger session.
            budget_usd:  Optional cost budget. Triggers warnings at 80%,
                         errors at 100%. None = no budget tracking.
            log_dir:     Where to write metrics JSONL. Defaults to config.
        """
        self.session_id = session_id
        self.budget_usd = budget_usd
        self.log_dir = log_dir or config.log_dir
        self.log_dir.mkdir(parents=True, exist_ok=True)

        # In-memory store for fast aggregation
        self._metrics: list[RunMetric] = []

        # JSONL file path (mirrors logger naming convention)
        today = datetime.now(timezone.utc).strftime("%Y%m%d")
        self._metrics_path = self.log_dir / f"metrics_{session_id}_{today}.jsonl"

        # Load any existing metrics from today's file
        # (supports resuming a session across process restarts)
        self._load_existing_metrics()

        logger.debug(
            "TokenMonitor initialized | session={} | budget={}",
            session_id,
            f"${budget_usd:.4f}" if budget_usd else "none",
        )

    def _load_existing_metrics(self) -> None:
        """Reload today's metrics from disk into memory on startup."""
        if not self._metrics_path.exists():
            return
        count = 0
        with open(self._metrics_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    d = json.loads(line)
                    # Reconstruct RunMetric from dict
                    metric = RunMetric(
                        run_id=d.get("run_id", ""),
                        timestamp=d.get("timestamp", ""),
                        provider=d.get("provider", "unknown"),
                        model=d.get("model", "unknown"),
                        session_id=d.get("session_id", self.session_id),
                        input_tokens=d.get("input_tokens", 0),
                        output_tokens=d.get("output_tokens", 0),
                        total_tokens=d.get("total_tokens", 0),
                        context_tokens=d.get("context_tokens", 0),
                        estimated_cost_usd=d.get("estimated_cost_usd", 0.0),
                        api_latency_ms=d.get("api_latency_ms", 0.0),
                        wall_time_ms=d.get("wall_time_ms", 0.0),
                        context_score=d.get("context_score"),
                        context_grade=d.get("context_grade"),
                        tags=d.get("tags", []),
                    )
                    self._metrics.append(metric)
                    count += 1
                except (json.JSONDecodeError, KeyError):
                    continue
        if count:
            logger.debug("Loaded {} existing metrics from {}", count, self._metrics_path.name)

    def record(self, lens_result: Any) -> RunMetric:
        """
        Record metrics from a completed LensResult.

        Called automatically by ContextLens.run() after every inference.
        Also performs budget checks and emits appropriate log warnings.

        Args:
            lens_result: A LensResult instance (from lens.py).

        Returns:
            RunMetric: The recorded metric (for testing / chaining).
        """
        resp = lens_result.response
        ctx = lens_result.context_entry
        evaluation = getattr(lens_result, "evaluation", None)

        metric = RunMetric(
            run_id=resp.run_id or ctx.run_id,
            provider=resp.provider,
            model=resp.model,
            session_id=self.session_id,
            input_tokens=resp.input_tokens,
            output_tokens=resp.output_tokens,
            total_tokens=resp.total_tokens,
            context_tokens=ctx.total_tokens,
            estimated_cost_usd=resp.estimated_cost_usd,
            api_latency_ms=resp.latency_ms,
            wall_time_ms=lens_result.total_wall_time_ms,
            context_score=evaluation.overall_score if evaluation else None,
            context_grade=evaluation.grade if evaluation else None,
            tags=ctx.tags,
        )

        self._metrics.append(metric)
        self._persist_metric(metric)
        self._check_budget(metric)

        return metric

    def _persist_metric(self, metric: RunMetric) -> None:
        """Append metric to JSONL file. Never raises — log and continue."""
        try:
            with open(self._metrics_path, "a", encoding="utf-8") as f:
                f.write(json.dumps(metric.to_dict()) + "\n")
        except OSError as e:
            logger.error("Failed to persist metric: {}", e)

    def _check_budget(self, latest_metric: RunMetric) -> None:
        """
        Check cumulative session cost against budget.
        Emits loguru warnings/errors — not exceptions.
        In production, this is where you'd fire a webhook to Slack.
        """
        if self.budget_usd is None:
            return

        total_cost = sum(m.estimated_cost_usd for m in self._metrics)
        used_pct = (total_cost / self.budget_usd) * 100

        if used_pct >= 100:
            logger.error(
                "BUDGET EXCEEDED: ${:.6f} spent of ${:.4f} budget ({:.1f}%). "
                "Consider pausing inference.",
                total_cost, self.budget_usd, used_pct,
            )
        elif used_pct >= 80:
            logger.warning(
                "Budget warning: {:.1f}% used (${:.6f} of ${:.4f}). "
                "Approaching limit.",
                used_pct, total_cost, self.budget_usd,
            )
        else:
            logger.debug(
                "Budget: {:.1f}% used (${:.6f} of ${:.4f})",
                used_pct, total_cost, self.budget_usd,
            )

    # ------------------------------------------------------------------
    # Aggregation
    # ------------------------------------------------------------------

    def get_report(self) -> SessionReport:
        """
        Compute and return the full session report.

        Aggregates all recorded metrics into totals, percentiles,
        per-provider breakdowns, and budget status.
        """
        if not self._metrics:
            return self._empty_report()

        # --- Totals ---
        total_runs = len(self._metrics)
        total_tokens = sum(m.total_tokens for m in self._metrics)
        total_cost = sum(m.estimated_cost_usd for m in self._metrics)

        # --- Latency percentiles using numpy ---
        latencies = np.array([m.api_latency_ms for m in self._metrics])
        p50 = float(np.percentile(latencies, 50))
        p90 = float(np.percentile(latencies, 90))
        p99 = float(np.percentile(latencies, 99))
        lat_min = float(np.min(latencies))
        lat_max = float(np.max(latencies))

        # --- Per-provider breakdown ---
        by_provider: dict[str, ProviderStats] = {}
        for m in self._metrics:
            if m.provider not in by_provider:
                by_provider[m.provider] = ProviderStats(provider=m.provider)
            ps = by_provider[m.provider]
            ps.runs += 1
            ps.total_tokens += m.total_tokens
            ps.total_cost_usd += m.estimated_cost_usd
            ps.total_latency_ms += m.api_latency_ms
            ps.latencies.append(m.api_latency_ms)

        # --- Budget status ---
        budget_used_pct: float | None = None
        budget_status = "no_budget"
        if self.budget_usd is not None and self.budget_usd > 0:
            budget_used_pct = (total_cost / self.budget_usd) * 100
            if budget_used_pct >= 100:
                budget_status = "exceeded"
            elif budget_used_pct >= 80:
                budget_status = "warning"
            else:
                budget_status = "ok"

        # --- Quality summary ---
        scored_runs = [m for m in self._metrics if m.context_score is not None]
        avg_score: float | None = None
        passed_count: int | None = None
        if scored_runs:
            avg_score = sum(m.context_score for m in scored_runs) / len(scored_runs)
            passed_count = sum(1 for m in scored_runs if m.context_score >= 70)

        # --- Outlier runs ---
        most_expensive = max(self._metrics, key=lambda m: m.estimated_cost_usd)
        slowest = max(self._metrics, key=lambda m: m.api_latency_ms)

        return SessionReport(
            session_id=self.session_id,
            generated_at=datetime.now(timezone.utc).isoformat(),
            total_runs=total_runs,
            total_tokens=total_tokens,
            total_cost_usd=total_cost,
            avg_tokens_per_run=total_tokens / total_runs,
            avg_cost_per_run_usd=total_cost / total_runs,
            p50_latency_ms=p50,
            p90_latency_ms=p90,
            p99_latency_ms=p99,
            min_latency_ms=lat_min,
            max_latency_ms=lat_max,
            by_provider=by_provider,
            budget_usd=self.budget_usd,
            budget_used_pct=budget_used_pct,
            budget_status=budget_status,
            avg_context_score=avg_score,
            runs_passed_evaluation=passed_count,
            most_expensive_run=most_expensive,
            slowest_run=slowest,
        )

    def _empty_report(self) -> SessionReport:
        return SessionReport(
            session_id=self.session_id,
            generated_at=datetime.now(timezone.utc).isoformat(),
            total_runs=0,
            total_tokens=0,
            total_cost_usd=0.0,
            avg_tokens_per_run=0.0,
            avg_cost_per_run_usd=0.0,
            p50_latency_ms=0.0,
            p90_latency_ms=0.0,
            p99_latency_ms=0.0,
            min_latency_ms=0.0,
            max_latency_ms=0.0,
            by_provider={},
            budget_usd=self.budget_usd,
            budget_used_pct=None,
            budget_status="no_budget",
            avg_context_score=None,
            runs_passed_evaluation=None,
            most_expensive_run=None,
            slowest_run=None,
        )

    # ------------------------------------------------------------------
    # Rich terminal display
    # ------------------------------------------------------------------

    def print_report(self) -> None:
        """
        Print a full session monitoring report to the terminal.
        Called by `contextlens report` CLI command and at session end.
        """
        report = self.get_report()

        if report.total_runs == 0:
            console.print("[yellow]No runs recorded in this session.[/yellow]")
            return

        # ── Overview panel ──────────────────────────────────────────
        budget_line = ""
        if report.budget_usd is not None:
            color = {
                "ok": "green", "warning": "yellow",
                "exceeded": "red", "no_budget": "dim",
            }[report.budget_status]
            budget_line = (
                f"\n[{color}]Budget: ${report.total_cost_usd:.6f} "
                f"of ${report.budget_usd:.4f} "
                f"({report.budget_used_pct:.1f}%) — {report.budget_status.upper()}[/{color}]"
            )

        quality_line = ""
        if report.avg_context_score is not None:
            q_color = "green" if report.avg_context_score >= 70 else "yellow"
            quality_line = (
                f"\n[{q_color}]Avg context quality: "
                f"{report.avg_context_score:.1f}/100 | "
                f"Passed: {report.runs_passed_evaluation}/{report.total_runs}[/{q_color}]"
            )

        overview = (
            f"[bold]Session:[/bold] {report.session_id}   "
            f"[bold]Runs:[/bold] {report.total_runs}   "
            f"[bold]Total tokens:[/bold] {report.total_tokens:,}   "
            f"[bold]Total cost:[/bold] ${report.total_cost_usd:.6f}"
            f"{budget_line}{quality_line}"
        )
        console.print(Panel(overview, title="Session Overview", border_style="dim"))

        # ── Latency table ───────────────────────────────────────────
        lat_table = Table(
            title="Latency Distribution (API calls)",
            box=box.SIMPLE_HEAVY,
            show_header=True,
            header_style="bold",
        )
        lat_table.add_column("Percentile", width=14)
        lat_table.add_column("Latency (ms)", width=16)
        lat_table.add_row("p50 (median)", f"{report.p50_latency_ms:.0f}")
        lat_table.add_row("p90",          f"{report.p90_latency_ms:.0f}")
        lat_table.add_row("p99",          f"{report.p99_latency_ms:.0f}")
        lat_table.add_row("min",          f"{report.min_latency_ms:.0f}")
        lat_table.add_row("max",          f"{report.max_latency_ms:.0f}")
        console.print(lat_table)

        # ── Per-provider breakdown ──────────────────────────────────
        if report.by_provider:
            prov_table = Table(
                title="Provider Breakdown",
                box=box.SIMPLE_HEAVY,
                show_header=True,
                header_style="bold",
            )
            prov_table.add_column("Provider",         width=12)
            prov_table.add_column("Runs",             width=8)
            prov_table.add_column("Total tokens",     width=14)
            prov_table.add_column("Total cost (USD)", width=18)
            prov_table.add_column("Avg latency",      width=14)
            prov_table.add_column("Cost / run",       width=14)

            for name, ps in sorted(report.by_provider.items()):
                prov_table.add_row(
                    name,
                    str(ps.runs),
                    f"{ps.total_tokens:,}",
                    f"${ps.total_cost_usd:.6f}",
                    f"{ps.avg_latency_ms:.0f} ms",
                    f"${ps.avg_cost_per_run:.6f}",
                )
            console.print(prov_table)

        # ── Cost sparkline (ASCII) ──────────────────────────────────
        if len(self._metrics) >= 2:
            costs = [m.estimated_cost_usd for m in self._metrics[-20:]]
            max_c = max(costs) if max(costs) > 0 else 1
            bars = "▁▂▃▄▅▆▇█"
            spark = "".join(
                bars[min(7, int((c / max_c) * 8))] for c in costs
            )
            console.print(f"\n[dim]Cost per run (last {len(costs)}): {spark}[/dim]")

        # ── Outlier runs ────────────────────────────────────────────
        if report.most_expensive_run:
            mr = report.most_expensive_run
            console.print(
                f"\n[dim]Most expensive run: {mr.run_id[:12]}... "
                f"${mr.estimated_cost_usd:.6f} "
                f"({mr.provider}/{mr.model})[/dim]"
            )
        if report.slowest_run:
            sr = report.slowest_run
            console.print(
                f"[dim]Slowest run:       {sr.run_id[:12]}... "
                f"{sr.api_latency_ms:.0f}ms "
                f"({sr.provider}/{sr.model})[/dim]\n"
            )

    def export_report_json(self, output_path: Path | None = None) -> Path:
        """
        Export the session report as a JSON file.
        Used by CLI `contextlens report --export`.
        """
        report = self.get_report()
        out = output_path or (
            self.log_dir / f"report_{self.session_id}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.json"
        )
        with open(out, "w", encoding="utf-8") as f:
            json.dump(report.to_dict(), f, indent=2)
        logger.info("Report exported to {}", out)
        return out

    # convenience
    @property
    def total_cost_usd(self) -> float:
        return sum(m.estimated_cost_usd for m in self._metrics)

    @property
    def run_count(self) -> int:
        return len(self._metrics)